//
// Created by ben on 5/6/24.
//

#ifndef MYRAYLIBGAME_DEFS_H
#define MYRAYLIBGAME_DEFS_H

#define WINDOW_WIDTH 2560
#define WINDOW_HEIGHT 1440

#define TARGET_FPS 60

#define PADDLE_START_X 10
#define PADDLE_START_Y 60
#define PADDLE_WIDTH 25
#define PADDLE_HEIGHT 300
#define BALL_RADIUS 25
#define BALL_SPEED 600
#define PADDLE_SPEED 16

#endif //MYRAYLIBGAME_DEFS_H
